### ISSUE TITLE
Can't export skill 3.11

### ISSUE THREAD

**Issue by markliu06** [OmegaK2/PyPoE#124]
Use latest build downloaded and installed on this Sunday

command is right , pypoe_exporter wiki skill by_id [id] --write

have done setup perform beforehand

Display the red error code like this

Traceback (most recent call last):
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\handler.py", line 283, in wrapper
    parser = cls(base_path=temp_dir, parsed_args=pargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\parsers\skill.py", line 251, in __init__
    super().__init__(*args, **kwargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\parser.py", line 1470, in __init__
    language=config.get_option('language'),
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\dat.py", line 991, in __init__
    super().__init__(*args, **kwargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\shared\cache.py", line 128, in __init__
    read_func(file)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\dat.py", line 1005, in __getitem__
    return self.get_file(item).reader
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\dat.py", line 1087, in get_file
    df = self._create_instance(file_name)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\shared\cache.py", line 214, in _create_instance
    f.read(**self._get_read_args(file_name=file_name, *args, **kwargs))
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\shared\__init__.py", line 156, in get_read_buffer
    return function(*args, buffer=f, **kwargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\dat.py", line 946, in _read
    self.reader.read(buffer.read())
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\poe\file\dat.py", line 839, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "ActiveSkills.dat": Specification row size 110 vs real size 114

**Comment by markliu06** [comment]
Never mind , reinstall whole thing yield yellow text but at least it export correctly
