### ISSUE TITLE
mod export KeyError (post 3.13 patch)

### ISSUE THREAD

**Issue by markliu06** [OmegaK2/PyPoE#140]
Not sure the game has new mod text structure or not

> 11:31:00 Traceback (most recent call last):
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\handler.py", line 286, in wrapper
    result = func(parser, pargs, *args, **kwargs)
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\parsers\mods.py", line 163, in by_rowid
    return self._export(
  File "c:\users\t\documents\poewiki\pypoe\PyPoE\cli\exporter\wiki\parsers\mods.py", line 295, in _export
    MOD_SELL_PRICES[msp['Id']].items(), start=1):
KeyError: 'OverrideToWisdomFragment'

**Comment by markliu06** [comment]
Also this only affect new mod by using rowid and a range 21178 - 22000 (dummy value , can be smaller) to export them

It does not affect other mod

edit: tested, 21178-21187, and 21188-22000 (dummy range) are ok. The mod that cause this issue is located at rowid 21187-21188

**Comment by markliu06** [comment]
As of 3.13.1d, the mod is located at [22261, 22262)
