### ISSUE TITLE
Issue with ggpk_viewer

### ISSUE THREAD

**Issue by scottmudge** [OmegaK2/PyPoE#141]
I've encountered an issue with GGPK Viewer. It looks like the GGPK records are not sorting properly:

```
...\PyPoE\poe\file\ggpk.py:758: UserWarning: Invalid tag b'\x06\x00\x00\x00' - seeking next valid tag
  warnings.warn('Invalid tag %s - seeking next valid tag' % e.args)
Traceback (most recent call last):
  File "...\PyPoE\PyPoE\ui\ggpk_viewer\menu.py", line 91, in _update_ggpk_model
    self._thread.ggpk_file.directory.walk(self._ggpk_sort)
  File "...\PyPoE\PyPoE\poe\file\shared\__init__.py", line 556, in walk
    function(**data)
  File "...\PyPoE\PyPoE\ui\ggpk_viewer\menu.py", line 85, in _ggpk_sort
    node.children = sorted(node.children, key=sorter)
  File "...\PyPoE\PyPoE\ui\ggpk_viewer\menu.py", line 84, in <lambda>
    sorter = lambda obj: (isinstance(obj.record, FileRecord), obj.name)
AttributeError: 'str' object has no attribute 'record'
```

**Comment by markliu06** [comment]
What version of python you used? as well as pyside?

Also, can't remember the viewer work at all after 3.11.2 patch 

quote from first page

"UI will be reworked for bundle support and is not functional at the moment"
