### ISSUE TITLE
Difference in dat file and ggpk

### ISSUE THREAD

**Issue by ashcrok** [OmegaK2/PyPoE#23]
d:\workspace\PyPoE>pypoe_exporter dat json "out/dump.json"
15:09:26 Reading "c:\program files (x86)\steam\SteamApps\common\Path of Exile\content.ggpk"...
15:09:32 Reading .dat files
 67%|#####################################################7                          | 201/299 [00:05<00:02, 38.86it/s]
15:09:38 Traceback (most recent call last):
  File "d:\workspace\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "d:\workspace\pypoe\PyPoE\cli\exporter\dat\parsers\json.py", line 81, in handle
    dat_files = self._read_dat_files(args)
  File "d:\workspace\pypoe\PyPoE\cli\exporter\dat\handler.py", line 119, in _read_dat_files
    df.read(file_path_or_raw=node.record.extract(), use_dat_value=False)
  File "d:\workspace\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "d:\workspace\pypoe\PyPoE\poe\file\shared\__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "d:\workspace\pypoe\PyPoE\poe\file\dat.py", line 1010, in _read
    self.reader.read(buffer.read())
  File "d:\workspace\pypoe\PyPoE\poe\file\dat.py", line 903, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.dat.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "Races.dat": Specification row size 33 vs real size 37

**Comment by OmegaK2** [comment]
Should be fixed with the recent specification update.
