### ISSUE TITLE
after 3.1.2 update Mods.dat is giving errors

### ISSUE THREAD

**Issue by zaafar** [OmegaK2/PyPoE#46]
looks like there is some new data in Mods.dat (make sense, maybe mod tier info etc)
Don't have any expertise in solving that myself. Sorry if this is already reported multiple times, haven't checked discord or anything.

**Comment by zaafar** [comment]
looks like we have 4 more bytes.
```
Traceback (most recent call last):
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\ui\ggpk_viewer\core.py", line 217, in _view_record
    parent=self
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\ui\shared\file\handler.py", line 323, in get_widget
    dat_file.read(file_data, use_dat_value=True)
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\poe\file\shared\__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\poe\file\dat.py", line 919, in _read
    self.reader.read(buffer.read())
  File "c:\users\zaafa\desktop\ooo\pypoe\PyPoE\poe\file\dat.py", line 812, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "Mods.dat": Specification row size 261 vs real size 265
```
