### ISSUE TITLE
Error on export: "BaseItemTypes.dat": Specification row size 199 vs real size 203

### ISSUE THREAD

**Issue by lutel** [OmegaK2/PyPoE#58]
This is my first attempt to use PyPoe, I've tried to export data with command:

# pypoe_exporter dat json test.json

And i got this error:

13:11:21 Reading .dat files
  3%|██▌                                                                              | 11/354 [00:00<00:06, 52.13it/s]
13:11:21 Traceback (most recent call last):
  File "c:\users\tomek\desktop\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "c:\users\tomek\desktop\pypoe\PyPoE\cli\exporter\dat\parsers\json.py", line 102, in handle
    dat_files = self._read_dat_files(args)
  File "c:\users\tomek\desktop\pypoe\PyPoE\cli\exporter\dat\handler.py", line 130, in _read_dat_files
    df.read(file_path_or_raw=node.record.extract(), use_dat_value=False)
  File "c:\users\tomek\desktop\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "c:\users\tomek\desktop\pypoe\PyPoE\poe\file\shared\__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "c:\users\tomek\desktop\pypoe\PyPoE\poe\file\dat.py", line 919, in _read
    self.reader.read(buffer.read())
  File "c:\users\tomek\desktop\pypoe\PyPoE\poe\file\dat.py", line 812, in read
    'cast_size': self.table_record_length

**"BaseItemTypes.dat": Specification row size 199 vs real size 203**

How can I fix this?

**Comment by eps1lon** [comment]
The highlighted line is usually an indicator that the spec changed. We try to keep the spec synced but if the patch notes do not indicate a change or the change is irrelevant for our use cases the spec can become out of sync.

You can either wait till #59 is merged or apply the patch from the mentioned PR manually.

**Comment by lutel** [comment]
Thank you
