### ISSUE TITLE
can't run pypoe_ui (windows 10)

### ISSUE THREAD

**Issue by klipson3** [OmegaK2/PyPoE#66]
Tom@User-PC MINGW64 /e/PyPoE-dev
$ pypoe_ui

Tom@User-PC MINGW64 /e/PyPoE-dev
$ Traceback (most recent call last):
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36-32\Scripts\pypoe_ui-script.pyw", line 11, in <module>
    load_entry_point('PyPoE', 'gui_scripts', 'pypoe_ui')()
  File "c:\users\tom\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\tom\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\tom\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\tom\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "e:\pypoe-dev\PyPoE\ui\__init__.py", line 37, in <module>
    from PyPoE.ui.ggpk_viewer import GGPKViewerMainWindow
  File "e:\pypoe-dev\PyPoE\ui\ggpk_viewer\__init__.py", line 37, in <module>
    from PyPoE.ui.ggpk_viewer.core import GGPKViewerMainWindow
  File "e:\pypoe-dev\PyPoE\ui\ggpk_viewer\core.py", line 37, in <module>
    from PySide2.QtCore import *
ImportError: DLL load failed: ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒.

**Comment by Stridemann** [comment]
Same here. @klipson3  Did you found the solution?

Works fine until update "INCOMPATIBLE  - upgrade to PySide2"
I just installed python 3.6 x32, PySide2

**Comment by OmegaK2** [comment]
It looks to be an issue with pyside2 on windows 10 then, not sure what exactly is missing there or whether all win10 systems are affected

**Comment by brather1ng** [comment]
I think I got this too and solved it by separately installing PySide2 before installing PyPoE. At least I solved some error by installing packages separately, not sure if that was the same one.

**Comment by Stridemann** [comment]
Fixed it!
I just deleted my python 3.6.0 (and all other versions, launchers and all what python related) and installed 3.7.0 x64 (install to all users, pre-build base libraries). Works fine now!
Windows 8.1

@OmegaK2 maybe make sense to change python from 3.6 to 3.7.0 x64 in Readme on first page.

**Comment by Stridemann** [comment]
I just don't see the list of files
https://dl.dropboxusercontent.com/s/8uwitfah2yv00j6/pythonw_2018-12-27_12-57-35.png

After closing UI I have this errors:
https://dl.dropboxusercontent.com/s/7rdv5qzph314i5d/mintty_2018-12-27_13-00-56.png

```
$ Traceback (most recent call last):
  File "c:\users\stridemann\desktop\pypoe\PyPoE\ui\shared\file\model.py", line 183, in index
    return self.createIndex(row, column, self._data)
TypeError: 'PySide2.QtCore.QAbstractItemModel.createIndex' called with wrong argument types:
  PySide2.QtCore.QAbstractItemModel.createIndex(int, int, DirectoryNode)
Supported signatures:
  PySide2.QtCore.QAbstractItemModel.createIndex(int, int, quintptr = 0)
  PySide2.QtCore.QAbstractItemModel.createIndex(int, int, void = nullptr)
```

Was trying to install in both ways:
pip3 install -e .
pip3 install -e .[full]

```
$ pip install PySide2
Requirement already satisfied: PySide2 in c:\python37\lib\site-packages (5.12.0)
Requirement already satisfied: shiboken2 in c:\python37\lib\site-packages (from PySide2) (5.12.0)
```
```
$ pip install brotli
Requirement already satisfied: brotli in c:\python37\lib\site-packages (1.0.7)
```

**Comment by zaafar** [comment]
working fine for me on windows 10. here's my install version and stuff.

here is my output
```
C:\WINDOWS\system32>pip --version
pip 18.1 from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\pip (python 3.6)

C:\WINDOWS\system32>pip list
Package                  Version    Location
------------------------ ---------- ----------------------------------------------------
alabaster                0.7.12
asn1crypto               0.24.0
atomicwrites             1.2.1
attrs                    18.2.0
Babel                    2.6.0
Brotli                   1.0.7
certifi                  2018.10.15
cffi                     1.11.5
chardet                  3.0.4
colorama                 0.4.0
configobj                5.0.6
cryptography             2.3.1
docutils                 0.14
graphviz                 0.10.1
idna                     2.7
imagesize                1.1.0
Jinja2                   2.10
MarkupSafe               1.0
more-itertools           4.3.0
mwclient                 0.9.1
oauthlib                 2.1.0
packaging                18.0
pip                      18.1
pluggy                   0.8.0
py                       1.7.0
pycparser                2.19
Pygments                 2.2.0
PyMySQL                  0.9.2
PyOpenGL                 3.1.0
pyparsing                2.2.2
PyPoE                    1.0.0a0    
PySide2                  5.11.2
pytest                   3.9.3
pytz                     2018.6
requests                 2.20.0
requests-oauthlib        1.0.0
setuptools               40.5.0
six                      1.11.0
snowballstemmer          1.2.1
Sphinx                   1.8.1
sphinxcontrib-websupport 1.1.0
SQLAlchemy               1.2.12
tqdm                     4.28.1
urllib3                  1.24
```

**Comment by zaafar** [comment]
here you go. https://github.com/OmegaK2/PyPoE/issues/77#issuecomment-450272915

**Comment by OmegaK2** [comment]
One of the issues (with the script error) is specifically from pyside 5.12.0. 

The problem the OP has seems to be a known issue with pyside2 and using outdated virtualenv, see here:
https://wiki.qt.io/Qt_for_Python/Considerations#ImportError:_DLL_load_failed:_The_specified_module_could_not_be_found

**Comment by RUSshy** [comment]
i had to do:

``pip install PySide2`` on windows 10

Please add in readme doc, not everyone is familiar with python
