### ISSUE TITLE
pypoe and windows 10

### ISSUE THREAD

**Issue by eps1lon** [OmegaK2/PyPoE#7]
So i recently set up windows 10 and had (and still have) some issues. I dont know anything about python so pls review the suggested fixes.
- pypoe_ui doesnt do anything
- pypoe_exporter didnt start because:
  `Traceback (most recent call last):
  File "C:\Development\tools\python34\Scripts\pypoe_exporter-script.py", line 9, in <module>
    load_entry_point('PyPoE==1.0.0a0', 'console_scripts', 'pypoe_exporter')()
  File "C:\Development\tools\python34\lib\site-packages\pkg_resources\__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Development\tools\python34\lib\site-packages\pkg_resources\__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "C:\Development\tools\python34\lib\site-packages\pkg_resources\__init__.py", line 2310, in load
    return self.resolve()
  File "C:\Development\tools\python34\lib\site-packages\pkg_resources\__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\development\src\python\pypoe\PyPoE\cli\exporter\core.py", line 37, in <module>
    from PyPoE.poe.constants import VERSION, DISTRIBUTOR
  File "c:\development\src\python\pypoe\PyPoE\poe\__init__.py", line 35, in <module>
    from PyPoE.poe import constants, path, util, file, sim
  ImportError: cannot import name 'util'
  <class 'ImportError'>
  CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort`

There is no util directory or file in the poe directory so i removed the import. You prob mean util from another package but after the removal pypoe_exporter did everything i wanted it to.

**Comment by OmegaK2** [comment]
I think was too fast with closing this one; I fixed the second issue, but can you be more precise about pypoe_ui not doing anything?
If you can't, can you try running `python PyPoE/ui/__init__.py` and see what happens

**Comment by eps1lon** [comment]
`python PyPoE/ui/__init__.py` lead to
`Traceback (most recent call last):
  File "PyPoE/ui/__init__.py", line 37, in <module>
    from PyPoE.ui.ggpk_viewer import GGPKViewerMainWindow
  File "c:\development\src\python\pypoe\PyPoE\ui\__init__.py", line 37, in <module>
    from PyPoE.ui.ggpk_viewer import GGPKViewerMainWindow
  File "c:\development\src\python\pypoe\PyPoE\ui\ggpk_viewer\__init__.py", line 37, in <module>
    from PyPoE.ui.ggpk_viewer.core import GGPKViewerMainWindow
  File "c:\development\src\python\pypoe\PyPoE\ui\ggpk_viewer\core.py", line 37, in <module>
    from PySide.QtCore import *
ImportError: No module named 'PySide'`

neither `pip` nor `easy_install` would install PySide because of `error: Failed to find the MSVC compiler version 10.0 on your system.`. So i installed PySide 1.2.2.win-amd64 from https://download.qt.io/official_releases/pyside/ which solved the issue.
