### ISSUE TITLE
can't export dat -  Specification row size error

### ISSUE THREAD

**Issue by lutel** [OmegaK2/PyPoE#72]
Specification error, i've never had luck to run the export succesfully. Maybe some kind of mechanism could be developed, that in case of mismatch in specification, new "unknown" field is created in export?

10:26:09 Reading .dat files
 18%|█████████████████████▋                                                                                                  | 75/414 [00:01<00:06, 54.53it/s]
10:26:10 Traceback (most recent call last):
  File "/w/users/tomek/PyPoE/PyPoE/cli/core.py", line 145, in run
    code = args.func(args)
  File "/w/users/tomek/PyPoE/PyPoE/cli/exporter/dat/parsers/json.py", line 102, in handle
    dat_files = self._read_dat_files(args)
  File "/w/users/tomek/PyPoE/PyPoE/cli/exporter/dat/handler.py", line 124, in _read_dat_files
    df.read(file_path_or_raw=node.record.extract(), use_dat_value=False)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/shared/__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/shared/__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/dat.py", line 919, in _read
    self.reader.read(buffer.read())
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/dat.py", line 812, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "CustomLeagueMods.dat": Specification row size 46 vs real size 50

**Comment by aleskozina** [comment]
same here!
