### ISSUE TITLE
"GeometryAttack.dat": Specification row size 98 vs real size 102

### ISSUE THREAD

**Issue by lutel** [OmegaK2/PyPoE#76]
Latest snapshot, latest patch... Never had a luck to run it successfully. Could it at least ignore error and resume?

14:10:20 Reading "/w/energ/Content.ggpk"...

14:11:24 Reading .dat files
 34%|████████████████████████████████████████                                                                               | 149/443 [00:02<00:04, 68.23it/s]
14:11:26 Traceback (most recent call last):
  File "/w/users/tomek/PyPoE/PyPoE/cli/core.py", line 145, in run
    code = args.func(args)
  File "/w/users/tomek/PyPoE/PyPoE/cli/exporter/dat/parsers/json.py", line 102, in handle
    dat_files = self._read_dat_files(args)
  File "/w/users/tomek/PyPoE/PyPoE/cli/exporter/dat/handler.py", line 124, in _read_dat_files
    df.read(file_path_or_raw=node.record.extract(), use_dat_value=False)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/shared/__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/shared/__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/dat.py", line 919, in _read
    self.reader.read(buffer.read())
  File "/w/users/tomek/PyPoE/PyPoE/poe/file/dat.py", line 812, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "GeometryAttack.dat": Specification row size 98 vs real size 102

**Comment by zaafar** [comment]
Other than that following files also have invalid specifications

* MicrotransactionPeriodicCharacterEffectVariations.dat ( real size is a lot bigger than specified size )
* SafehouseCraftingSpree.dat ( real size is double )
* SupporterPackSets.dat ( add 4byte object will fix this maybe int )

if they are really not that important maybe we can just remove them so the cli doesn't crash when exporting these files into json format.
