### ISSUE TITLE
ValueError: Did not find data magic number

### ISSUE THREAD

**Issue by doomruller** [OmegaK2/PyPoE#91]
Windows 10 python 3.7.3
1) pypoe_ui
2) file -> open ggpk
3) select data/Mods.dat
get this error when trying to view.
ValueError occurred when trying to open Mods.dat: 

Traceback (most recent call last):
  File "c:\users\jason\documents\pypoe\PyPoE\ui\ggpk_viewer\core.py", line 217, in _view_record
    parent=self
  File "c:\users\jason\documents\pypoe\PyPoE\ui\shared\file\handler.py", line 324, in get_widget
    dat_file.read(file_data, use_dat_value=True)
  File "c:\users\jason\documents\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "c:\users\jason\documents\pypoe\PyPoE\poe\file\shared\__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "c:\users\jason\documents\pypoe\PyPoE\poe\file\dat.py", line 917, in _read
    self.reader.read(buffer.read())
  File "c:\users\jason\documents\pypoe\PyPoE\poe\file\dat.py", line 787, in read
    'file': self.file_name,
ValueError: Did not find data magic number in "Mods.dat"

Get something similar when trying to use CLI.

**Comment by Svampen** [comment]
Any update on this issue?
I'm have the same problem with the latest content.ggpk (3.7.5.1)


15:49:04 Reading "/poe/Content.ggpk"...
15:50:21 Reading .dat files
  0%|                                                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
15:50:21 Traceback (most recent call last):
  File "/pypoe/PyPoE/cli/core.py", line 145, in run
    code = args.func(args)
  File "/pypoe/PyPoE/cli/exporter/dat/parsers/json.py", line 109, in handle
    dat_files = self._read_dat_files(args)
  File "/pypoe/PyPoE/cli/exporter/dat/handler.py", line 131, in _read_dat_files
    df.read(file_path_or_raw=node.record.extract(), use_dat_value=False)
  File "/pypoe/PyPoE/poe/file/shared/__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "/pypoe/PyPoE/poe/file/shared/__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "/pypoe/PyPoE/poe/file/dat.py", line 917, in _read
    self.reader.read(buffer.read())
  File "/pypoe/PyPoE/poe/file/dat.py", line 787, in read
    'file': self.file_name,
ValueError: Did not find data magic number in "BaseItemTypes.dat"
